@startmindmap
*Sistema de gestão do teste de progresso

**Possíveis problemas

***Grande quantidade de alunos
***Muitos cursos
***Proporção aluno por sala
***Organização dos fiscais


**Usuários
***Coordenção 
***Professores
***Aluno

**Recursos
***Salas
***Unidades

@endmindmap